service: event-gateway-tracer

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

plugins:
  - serverless-finch

custom:
  client:
    bucketName: event-gateaway-tracer
    distributionFolder: build
    indexDocument: index.html
    errorDocument: error.html
